on: [push]

name: build
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun build --compile --minify --sourcemap --target=bun-linux-x64 mpt.ts --outfile build/mpt
      - run: bun build --compile --minify --sourcemap --target=bun-windows-x64 mpt.ts --outfile build/mpt.exe

      # Upload the build artifact
      - uses: actions/upload-artifact@v2
        with:
          path: build